spring:
  application:
    name: br-cnes-hub-api
  cache:
    type: caffeine
  main:
    web-application-type: servlet

cneshub:
  ingest:
    baseUrl: https://opendatasus.saude.gov.br/api/3/action
    datasets:
      estabelecimentos: <RESOURCE_ID>
  cache:
    ttl: 5m
  security:
    apiKeyEnabled: false
    apiKey: trocar-em-producao

resilience4j:
  circuitbreaker:
    instances:
      ckan:
        sliding-window-size: 20
        failure-rate-threshold: 50
  retry:
    instances:
      ckan:
        max-attempts: 3
        wait-duration: 500ms
  ratelimiter:
    instances:
      ckan:
        limit-for-period: 10
        limit-refresh-period: 1s
