spring:
  application:
    name: br-cnes-hub-api
  main:
    web-application-type: servlet

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    url: /v1/api-docs

cneshub:
  ingest:
    baseUrl: https://opendatasus.saude.gov.br/api/3/action
    datasets:
      estabelecimentos: <RESOURCE_ID>
  security:
    apiKeyEnabled: false
    apiKey: trocar-em-producao

resilience4j:
  circuitbreaker:
    instances:
      ckan:
        sliding-window-size: 20
        failure-rate-threshold: 50
  retry:
    instances:
      ckan:
        max-attempts: 3
        wait-duration: 500ms
  ratelimiter:
    instances:
      ckan:
        limit-for-period: 10
        limit-refresh-period: 1s
