server:
  port: 8080

spring:
  application:
    name: br-cnes-hub-api
  datasource:
    url: jdbc:postgresql://localhost:5432/cneshub
    username: cnes
    password: cnes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  flyway:
    enabled: true
  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

cneshub:
  security:
    apiKeyEnabled: false
    apiKey: trocar-em-producao
  ingest:
    baseUrl: https://opendatasus.saude.gov.br/api/3/action
    datasets:
      estabelecimentos: RESOURCE_ID

resilience4j:
  circuitbreaker:
    instances:
      ckan:
        sliding-window-size: 20
        failure-rate-threshold: 50
  retry:
    instances:
      ckan:
        max-attempts: 3
        wait-duration: 500ms
  ratelimiter:
    instances:
      ckan:
        limit-for-period: 10
        limit-refresh-period: 1s
