server:
  port: 8080

spring:
  application:
    name: br-cnes-hub-api
  datasource:
    url: jdbc:postgresql://localhost:5432/cneshub
    username: cnes
    password: cnes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  flyway:
    enabled: true
  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

cneshub:
  security:
    apiKeyEnabled: false
    apiKey: trocar-em-producao
  ingest:
    baseUrl: https://dados.gov.br
    datasets:
      estabelecimentos: RESOURCE_ID
